# Generated by Django 4.2 on 2025-03-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_admin', '0003_alter_appointment_doctor_alter_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='doctor_images/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(max_length=255),
        ),
    ]
