# Generated by Django 4.2 on 2025-03-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_admin', '0004_remove_doctor_experience_doctor_years_of_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(upload_to='doctor_images/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(max_length=100),
        ),
    ]
